### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getCursorBufferPositions' of undefined

### ISSUE THREAD

**Issue by tabarra** [garralab/fast-duplicate#1]
[Enter steps to reproduce below:]
1. click on a line
2. ctrl+shift+up / ctrl+shift+down

**Atom Version**: 1.0.0
**System**: Unknown Windows Version
**Thrown From**: [fast-duplicate](https://github.com/garralab/fast-duplicate) package, v1.0.0
### Stack Trace

Uncaught TypeError: Cannot read property 'getCursorBufferPositions' of undefined

```
At C:\Users\Tabarra\.atom\packages\fast-duplicate\lib\fast-duplicate.coffee:3

TypeError: Cannot read property 'getCursorBufferPositions' of undefined
  at C:\Users\Tabarra\.atom\packages\fast-duplicate\lib\fast-duplicate.coffee:3:15
  at getCursors (C:\Users\Tabarra\.atom\packages\fast-duplicate\lib\fast-duplicate.coffee:17:7)
  at Object.module.exports.up (C:\Users\Tabarra\.atom\packages\fast-duplicate\lib\fast-duplicate.coffee:50:15)
  at atom-workspace.<anonymous> (C:\Users\Tabarra\.atom\packages\fast-duplicate\lib\fast-duplicate.coffee:33:76)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Tabarra\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:241:29)
  at C:\Users\Tabarra\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Tabarra\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Tabarra\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Tabarra\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:180:20)

```
### Commands

```
     -0:07.2.0 fast-duplicate:duplicate-up (atom-text-editor.editor.is-focused)
     -0:06.4.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
fast-duplicate, v1.0.0
file-icons, v1.5.8
less-than-slash, v0.6.0
linter, v1.0.9
linter-php, v0.0.15
overscroll, v0.1.0
pigments, v0.8.0

# Dev
No dev packages
```

**Comment by pruge** [comment]
lib/fast-duplicate.coffee

```
-    editor = atom.workspace.activePaneItem
+    editor = atom.workspace.paneContainer.activePane.activeItem
```
