### ISSUE TITLE
Uncaught TypeError: Cannot read property 'duplicateLines' of undefined

### ISSUE THREAD

**Issue by kraxarn** [garralab/fast-duplicate#2]
[Enter steps to reproduce below:]
1. Ctrl-Shift-Up/Down

**Atom Version**: 1.0.0
**System**: Ubuntu 15.04
**Thrown From**: [fast-duplicate](https://github.com/garralab/fast-duplicate) package, v1.0.0
### Stack Trace

Uncaught TypeError: Cannot read property 'duplicateLines' of undefined

```
At /home/kraxarn/.atom/packages/fast-duplicate/lib/fast-duplicate.coffee:36

TypeError: Cannot read property 'duplicateLines' of undefined
  at Object.module.exports.down (/home/kraxarn/.atom/packages/fast-duplicate/lib/fast-duplicate.coffee:36:11)
  at atom-workspace.<anonymous> (/home/kraxarn/.atom/packages/fast-duplicate/lib/fast-duplicate.coffee:32:78)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:180:20)

```
### Commands

```
     -5:25.3.0 core:move-right (atom-text-editor.editor.is-focused)
  9x -5:21 core:backspace (atom-text-editor.editor.is-focused)
  3x -4:05.5.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:04.8.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:02.7.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -4:00.5.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:39.3.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:39 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -3:24.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:05.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:18.7.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:18.2.0 core:move-down (atom-text-editor.editor.is-focused)
  3x -0:16.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:04.9.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -0:03.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.3.0 fast-duplicate:duplicate-down (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "autoclose-html"
    ],
    "autoHideMenuBar": true
  }
}
```
### Installed Packages

``` coffee
# User
fast-duplicate, v1.0.0

# Dev
No dev packages
```

**Comment by handonam** [comment]
also had this happen.  Wish the contributor would respond back..

**Comment by pruge** [comment]
lib/fast-duplicate.coffee

```
-    editor = atom.workspace.activePaneItem
+    editor = atom.workspace.paneContainer.activePane.activeItem
```
